### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MykhailoDm** [MykhailoDm/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by john-johnsonni** [comment]
― I do not compete with other fighters, the only competition that challenges me is me, myself, my anxiety and my bean soup. As a fighter, friend and employee, I am known as contemplative, tortured, positively mad and driven. Stable and concentrated whooping 99% of 50 % of the time.
