### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by MykhailoDm** [MykhailoDm/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by john-johnsonni** [comment]
LIFE & EDUCATION
To live is to fight, and to fight is to live. There also other things about life like food and air but most important is fight! Though, it is recommended you learn to breathe first.

LANGUAGES
🇺🇸 ENGLISH 🇨🇳 MANDARIN 🇯🇵 JAPANESE

SKILLS
KARATE, MORE KARATE, EVEN MORE KARATE, SUPER COOL MUSCLE FLEXING, COOKING

CHARACTER
NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE SENSUAL GOOD ECCENTRIC

LIFE LESSON
You must defeat yourself to stand a chance against the WORST enemy of yours - yourself.

LIKES 😃
GI VEGETABLES MEAT BLOOD CINEMA OPERA BALLET WRESTLING CATS

DISLIKES 😞
BISONS GHOSTS ARMOR LACK OF HAIR DOGS

WANTS 🥺
JOB MONEY BE FIT FRIEND TO FIGHT AKUMA WITH METAL JOACHIM FIGURINE
